---
  - name: Application server
    include_role:
        name: common
        tasks_from: "{{item}}"
    loop:  
      - recordtime
      - copy
      - manageservice
      - updatesystem
      - installpkgs
      - useradd
